### ISSUE TITLE
Hook on methods with struct parameters garble the struct

### ISSUE THREAD

**Issue by harbingerofme** [MonoMod/MonoMod#59] opened 2020-01-12 14:29 UTC
### Description
Using `v19.11.05.01` and Runtimedetour for `On.etc` hooks, applying a hook on a method which has a struct as one of its parameters causes subsequent `orig(,..., struct,...)` calls to use a struct which seems garbled. The struct in the hook delegate itself will behave normally.

### Example
```cs
//Original Code:
public struct MyStruct
{
    bool myBool;
    string myString;
}
public static void PrintConditionalStruct(MyStruct parameter)
{
    if(parameter.myBool){
        Debug.Log(myString);
    }
}
//Calling code:
var displayThis = new myStruct { true, "WORD This should be displayed!" };
PrintConditionalStruct(displayThis);
// The hook:
On.PrintConditionalStruct += (orig, param) =>
{
    if(param.myBool && param.myString.StartsWith("WORD"){
        Debug.Log("Replaced!");
        param.myString = param.myString.Substring(5);
        }
    orig(param);
}
```
Then the expected result would be:
`Replaced!`
`This should be displayed!`
However, currently I expect this to display just `Replaced!` instead.

We've encountered this issue in various places when modding risk of rain 2
In code Examples are `RoR2.Chat.CCSay`, `RoR2.InteractableSpawnCard.DoSpawn`

**Comment by aaay-aaay** [comment] 2020-01-12 15:11
If instead of taking the struct that was passed in as a parameter and passing it to the orig, what if you created a completely new struct within the hook delegate and passed that through instead?

It wouldn't exactly make sense for that to change anything but with this kind of thing you have to try things that don't exactly make much sense (speaking from experience, we have hooked methods in Enum with dynamic methods and had one issue which was solved by not hooking GetTypeCode for reasons we still don't understand)

(also we're pastebin.com/q3BTYZc9#3020 on the discord, ask us there if you want to know why we're referring to ourself as "we")

**Comment by harbingerofme** [comment] 2020-01-12 16:32
This disables the command `ccsay`
```csharp
On.RoR2.Chat.CCSay += (orig, args)=>
{
    orig(args);
};
```
This still disables the command:
```cs
On.RoR2.Chat.CCSay += (orig, args)=>
{
    RoR2.ConCommandArgs newArgs = new RoR2.ConCommandArgs { userArgs = args.userArgs, sender = args.sender, commandName = args.commandName };
    orig(newArgs);
};
```

**Comment by 0x0ade** [comment] 2020-01-12 16:52
Something that would really help with fixing the issue is a test case that can be replicated outside of any game, ideally a unit test. Until then I'm very limited in being able to debug it.

Also, this seems to describe a very similar issue with some additional info: https://github.com/EverestAPI/Everest/issues/66

**Comment by 0x0ade** [comment] 2020-03-05 15:21
Fixed by https://github.com/MonoMod/MonoMod/commit/016635a2101b3ee85da1ca04572037aa028e731b

**Closed by 0x0ade** 2020-03-05 15:21 UTC
Labels: bug
