### ISSUE TITLE
MonoMod.RuntimeDetour Build Failed!!

### ISSUE THREAD

**Issue by ZeeDEU** [MonoMod/MonoMod#54] opened 2019-07-23 20:18 UTC
How i can fix this?

Error Log:

```
1>------ Build started: Project: MonoMod.Utils, Configuration: Debug Any CPU ------
1>DynDll.cs(52,17,52,31): error CS0103: The name 'PlatformHelper' does not exist in the current context
1>DynDll.cs(52,35,52,43): error CS0103: The name 'Platform' does not exist in the current context
1>Cil\ILReferenceBag.cs(74,20,74,43): error CS0246: The type or namespace name 'DynamicMethodDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>Cil\ILReferenceBag.cs(74,60,74,83): error CS0246: The type or namespace name 'DynamicMethodDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>DynDll.cs(101,17,101,31): error CS0103: The name 'PlatformHelper' does not exist in the current context
1>DynDll.cs(101,35,101,43): error CS0103: The name 'Platform' does not exist in the current context
1>DynDll.cs(122,17,122,31): error CS0103: The name 'PlatformHelper' does not exist in the current context
1>DynDll.cs(122,35,122,43): error CS0103: The name 'Platform' does not exist in the current context
1>DynDll.cs(152,17,152,31): error CS0103: The name 'PlatformHelper' does not exist in the current context
1>DynDll.cs(152,35,152,43): error CS0103: The name 'Platform' does not exist in the current context
1>Extensions.cs(154,44,154,58): error CS1061: 'MethodInfo' does not contain a definition for 'CreateDelegate' and no accessible extension method 'CreateDelegate' accepting a first argument of type 'MethodInfo' could be found (are you missing a using directive or an assembly reference?)
1>Cil\ILContext.cs(60,20,60,39): error CS1061: 'MethodDefinition' does not contain a definition for 'ConvertShortLongOps' and no accessible extension method 'ConvertShortLongOps' accepting a first argument of type 'MethodDefinition' could be found (are you missing a using directive or an assembly reference?)
1>Extensions.cs(181,50,181,64): error CS1061: 'MethodInfo' does not contain a definition for 'CreateDelegate' and no accessible extension method 'CreateDelegate' accepting a first argument of type 'MethodInfo' could be found (are you missing a using directive or an assembly reference?)
1>FastReflectionHelper.cs(19,78,19,83): error CS1061: 'MethodBase' does not contain a definition for 'GetID' and no accessible extension method 'GetID' accepting a first argument of type 'MethodBase' could be found (are you missing a using directive or an assembly reference?)
1>Cil\ILPatternMatchingExt.cs(401,50,401,55): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>FastReflectionHelper.cs(117,82,117,87): error CS1061: 'MethodBase' does not contain a definition for 'GetID' and no accessible extension method 'GetID' accepting a first argument of type 'MethodBase' could be found (are you missing a using directive or an assembly reference?)
1>Cil\ILPatternMatchingExt.cs(420,51,420,56): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(439,55,439,60): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(458,61,458,66): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(1091,52,1091,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1093,52,1093,57): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1108,52,1108,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1110,52,1110,57): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1137,67,1137,76): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1139,67,1139,71): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1150,53,1150,58): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(1165,56,1165,65): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1167,56,1167,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1182,53,1182,62): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1184,53,1184,58): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1206,52,1206,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1208,52,1208,57): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1234,52,1234,57): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1253,53,1253,58): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1272,52,1272,57): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1291,53,1291,58): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1310,54,1310,59): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1329,53,1329,58): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1344,52,1344,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1346,52,1346,57): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1431,50,1431,59): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1433,50,1433,55): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1448,53,1448,62): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1450,53,1450,58): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1472,54,1472,63): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1474,54,1474,59): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1622,56,1622,65): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1624,56,1624,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1639,56,1639,65): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1641,56,1641,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1656,55,1656,64): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1658,55,1658,60): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1729,56,1729,65): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1731,56,1731,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1753,55,1753,64): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1755,55,1755,60): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1947,52,1947,57): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(1966,56,1966,61): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(2104,54,2104,63): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2106,54,2106,59): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2121,58,2121,67): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2123,58,2123,63): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2170,53,2170,62): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2172,53,2172,58): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Done building project "MonoMod.Utils.csproj" -- FAILED.
1>Cil\ILContext.cs(60,20,60,39): error CS1061: 'MethodDefinition' does not contain a definition for 'ConvertShortLongOps' and no accessible extension method 'ConvertShortLongOps' accepting a first argument of type 'MethodDefinition' could be found (are you missing a using directive or an assembly reference?)
1>Cil\ILReferenceBag.cs(74,20,74,43): error CS0246: The type or namespace name 'DynamicMethodDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>Cil\ILReferenceBag.cs(74,60,74,83): error CS0246: The type or namespace name 'DynamicMethodDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>Cil\ILPatternMatchingExt.cs(401,50,401,55): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>DynDll.cs(52,17,52,31): error CS0103: The name 'PlatformHelper' does not exist in the current context
1>DynDll.cs(52,35,52,43): error CS0103: The name 'Platform' does not exist in the current context
1>Cil\ILPatternMatchingExt.cs(420,51,420,56): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>DynDll.cs(101,17,101,31): error CS0103: The name 'PlatformHelper' does not exist in the current context
1>DynDll.cs(101,35,101,43): error CS0103: The name 'Platform' does not exist in the current context
1>DynDll.cs(122,17,122,31): error CS0103: The name 'PlatformHelper' does not exist in the current context
1>DynDll.cs(122,35,122,43): error CS0103: The name 'Platform' does not exist in the current context
1>Cil\ILPatternMatchingExt.cs(439,55,439,60): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>DynDll.cs(152,17,152,31): error CS0103: The name 'PlatformHelper' does not exist in the current context
1>DynDll.cs(152,35,152,43): error CS0103: The name 'Platform' does not exist in the current context
1>Cil\ILPatternMatchingExt.cs(458,61,458,66): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>FastReflectionHelper.cs(19,78,19,83): error CS1061: 'MethodBase' does not contain a definition for 'GetID' and no accessible extension method 'GetID' accepting a first argument of type 'MethodBase' could be found (are you missing a using directive or an assembly reference?)
1>FastReflectionHelper.cs(117,82,117,87): error CS1061: 'MethodBase' does not contain a definition for 'GetID' and no accessible extension method 'GetID' accepting a first argument of type 'MethodBase' could be found (are you missing a using directive or an assembly reference?)
1>Cil\ILPatternMatchingExt.cs(1091,52,1091,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1093,52,1093,57): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1108,52,1108,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1110,52,1110,57): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1137,67,1137,76): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1139,67,1139,71): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1150,53,1150,58): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(1165,56,1165,65): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1167,56,1167,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1182,53,1182,62): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1184,53,1184,58): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1206,52,1206,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1208,52,1208,57): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1234,52,1234,57): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1253,53,1253,58): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1272,52,1272,57): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1291,53,1291,58): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1310,54,1310,59): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1329,53,1329,58): error CS1503: Argument 2: cannot convert from 'System.Reflection.FieldInfo' to 'string'
1>Cil\ILPatternMatchingExt.cs(1344,52,1344,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1346,52,1346,57): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1431,50,1431,59): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1433,50,1433,55): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1448,53,1448,62): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1450,53,1450,58): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1472,54,1472,63): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1474,54,1474,59): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1622,56,1622,65): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1624,56,1624,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1639,56,1639,65): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1641,56,1641,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1656,55,1656,64): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1658,55,1658,60): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1729,56,1729,65): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1731,56,1731,61): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1753,55,1753,64): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1755,55,1755,60): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(1947,52,1947,57): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(1966,56,1966,61): error CS1503: Argument 2: cannot convert from 'System.Reflection.MethodBase' to 'string'
1>Cil\ILPatternMatchingExt.cs(2104,54,2104,63): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2106,54,2106,59): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2121,58,2121,67): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2123,58,2123,63): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2170,53,2170,62): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Cil\ILPatternMatchingExt.cs(2172,53,2172,58): error CS1503: Argument 2: cannot convert from 'System.Type' to 'string'
1>Done building project "MonoMod.Utils.csproj" -- FAILED.
2>------ Build started: Project: MonoMod.RuntimeDetour, Configuration: Debug Any CPU ------
2>CSC : error CS0006: Metadata file 'C:\Users\kikuk\Desktop\MonoMod-master\MonoMod.Utils\bin\Debug\net35\MonoMod.Utils.dll' could not be found
2>Done building project "MonoMod.RuntimeDetour.csproj" -- FAILED.
2>CSC : error CS0006: Metadata file 'C:\Users\kikuk\Desktop\MonoMod-master\MonoMod.Utils\bin\Debug\netstandard2.0\MonoMod.Utils.dll' could not be found
2>Done building project "MonoMod.RuntimeDetour.csproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by 0x0ade** [comment] 2019-07-23 20:35
1. Have you cloned the repository recursively (including submodules)?
2. What are you building with, and what version? Visual Studio on Windows? On macOS? msbuild via Mono?
3. Can you please use \`\`\`code blocks\`\`\` next time you provide a log? They'll look like this:

```
code blocks
```

**Comment by ZeeDEU** [comment] 2019-07-23 20:42
1. Have you cloned the repository recursively (including submodules)?
2. What are you building with, and what version? Visual Studio on Windows? On macOS? msbuild via Mono?

1. No
2. Im using Visual Studio 2019 (Windows 10 64bit) wdym with "msbuild via Mono"

i simply followed this tutorial:
https://www.youtube.com/watch?v=f9KdczInvDM

**Comment by 0x0ade** [comment] 2019-07-23 21:01
Can't watch the tutorial right now (I'm on vacation), but judging by the date and your response to 1, it simply is outdated.

You'll either need to clone recursively, or initialize all submodules after cloning.

If you've downloaded the .zip via GitHub, you'll need to fill the MonoMod.Common folder with the contents of this repository: https://github.com/MonoMod/MonoMod.Common

I'll close this issue as it's not a bug with MonoMod itself, but feel free to continue this discussion here or on Discord (invite in readme) :)

**Closed by 0x0ade** 2019-07-23 21:01 UTC
Labels: bug
